global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: identity
    static_configs:
      - targets: ["identity:8001"]

  - job_name: catalog
    static_configs:
      - targets: ["catalog:8002"]
