global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: identity
    metrics_path: /metrics
    static_configs:
      - targets: ["identity:8001"]

  - job_name: course
    metrics_path: /metrics
    static_configs:
      - targets: ["course:8002"]

  - job_name: enrollment
    metrics_path: /metrics
    static_configs:
      - targets: ["enrollment:8003"]

  - job_name: payment
    metrics_path: /metrics
    static_configs:
      - targets: ["payment:8004"]

  - job_name: notification
    metrics_path: /metrics
    static_configs:
      - targets: ["notification:8005"]

  - job_name: ai
    metrics_path: /metrics
    static_configs:
      - targets: ["ai:8006"]
