[project]
name = "seed"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30",
    "faker>=33",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
